# LINK TO TEAM VIDEO
# https://

  .syntax unified
  .cpu cortex-m4
  .fpu softvfp
  .thumb
  
  .global Main
  .global SysTick_Handler
  .global EXTI0_IRQHandler

  @ Definitions are in definitions.s to keep this file "clean"
  #include "definitions.S"

  .equ    BLINK_PERIOD, 600 
  .equ    a, 5
  .equ    c, 1
  .equ    m, 8

  .section .text
  .type Main, %function
Main:
  PUSH  {R4-R5,LR}


  @
  @ Prepare GPIO Port E Pin 9 for output (LED LD3)
  @ We'll blink LED LD3 (the orange LED)
  @

  @ Enable GPIO port E by enabling its clock
  LDR     R4, =RCC_AHBENR
  LDR     R5, [R4]
  ORR     R5, R5, #(0b1 << (RCC_AHBENR_GPIOEEN_BIT))
  STR     R5, [R4]

  @ Configure LD3 for output
  @   by setting bits 27:26 of GPIOE_MODER to 01 (GPIO Port E Mode Register)
  @   (by BIClearing then ORRing)
  LDR     R4, =GPIOE_MODER
  LDR     R5, =0x55550000

  STR     R5, [R4]                      @ Write 

  @ Initialise the first countdown

  LDR     R4, =blink_countdown
  LDR     R5, =0
  STR     R5, [R4]  

  LDR   R4, =i
  MOV   R5, #0
  STR   R5, [R4]
  



  @ Configure SysTick Timer to generate an interrupt every 1ms

  LDR   R4, =SCB_ICSR               @ Clear any pre-existing interrupts
  LDR   R5, =SCB_ICSR_PENDSTCLR     @
  STR   R5, [R4]                    @

  LDR   R4, =SYSTICK_CSR            @ Stop SysTick timer
  LDR   R5, =0                      @   by writing 0 to CSR
  STR   R5, [R4]                    @   CSR is the Control and Status Register
  
  LDR   R4, =SYSTICK_LOAD           @ Set SysTick LOAD for 1ms delay
  LDR   R5, =7999                   @ Assuming 8MHz clock
  STR   R5, [R4]                    @ 

  LDR   R4, =SYSTICK_VAL            @   Reset SysTick internal counter to 0
  LDR   R5, =0x1                    @     by writing any value
  STR   R5, [R4]

  LDR   R4, =SYSTICK_CSR            @   Start SysTick timer by setting CSR to 0x7
  LDR   R5, =0x7                    @     set CLKSOURCE (bit 2) to system clock (1)
  STR   R5, [R4]                    @     set TICKINT (bit 1) to 1 to enable interrupts
                                      @     set ENABLE (bit 0) to 1


  @
  @ Prepare external interrupt Line 0 (USER pushbutton)
  @ We'll count the number of times the button is pressed
  @

  @ Initialise count to zero
  LDR   R4, =button_count             @ count = 0;
  MOV   R5, #0                        @
  STR   R5, [R4]                      @

  @ Configure USER pushbutton (GPIO Port A Pin 0 on STM32F3 Discovery
  @   kit) to use the EXTI0 external interrupt signal
  @ Determined by bits 3..0 of the External Interrrupt Control
  @   Register (EXTIICR)
  LDR     R4, =SYSCFG_EXTIICR1
  LDR     R5, [R4]
  BIC     R5, R5, #0b1111
  STR     R5, [R4]

  @ Enable (unmask) interrupts on external interrupt Line0
  LDR     R4, =EXTI_IMR
  LDR     R5, [R4]
  ORR     R5, R5, #1
  STR     R5, [R4]

  @ Set falling edge detection on Line0
  LDR     R4, =EXTI_RTSR
  LDR     R5, [R4]
  ORR     R5, R5, #1
  STR     R5, [R4]

  LDR     R4, =EXTI_FTSR
  LDR     R5, [R4]
  ORR     R5, R5, #1
  STR     R5, [R4]

  @ Enable NVIC interrupt #6 (external interrupt Line0)
  LDR     R4, =NVIC_ISER
  MOV     R5, #(1<<6)
  STR     R5, [R4]

  @ Nothing else to do in Main
  @ Idle loop forever (welcome to interrupts!!)
Idle_Loop:
  B     Idle_Loop
  
End_Main:
  POP   {R4-R5,PC}



@
@ SysTick interrupt handler (blink LED LD3)
@
  .type  SysTick_Handler, %function
SysTick_Handler:

  PUSH  {R4-R7, LR}

  LDR   R4, =game_started
  LDR   R5, [R4]
  CMP   R5, #0
  BNE   .LelseGameStarted

  LDR   R4, =button_is_pressed
  LDR   R5, [R4]
  CMP   R5, #0
  BEQ   .LelseNotPressed        @ if (button_is_pressed) {

  LDR   R4, =pressed_time
  LDR   R5, [R4]
  ADD   R5, R5, #1              @   pressed_time += 1
  STR   R5, [R4]
  B     .LendIfPressed
.LelseNotPressed:               @ } else {
  LDR   R4, =pressed_time
  LDR   R5, [R4]
  CMP   R5, #0
  BEQ   .LendIfPressed

  MOV   R8, R5                  @   x0 = pressed_time
  LDR   R4, =random_value
  LDR   R5, [R4]                @   n = random_value

  MOV   R6, #0                  @   
.LwhGenLights:                  @   for (int i = 0; i < n; i++) {
  CMP   R6, R5
  BGE   .LendWhGenLights

  MOV   R7, #a
  MUL   R8, R8, R7              @       x1 = x0 * a + c
  ADD   R8, R8, #c
  AND   R8, #7                  @       x1 = x1 && 7
                                @       same as % 8
  LDR   R7, =random_lights
  STR   R8, [R7, R6, LSL #2]    @       word[random_lights] = x1

  ADD   R6, R6, #1
  B     .LwhGenLights
.LendWhGenLights:               @   }
  LDR   R4, =game_started           @ game_started = 1
  MOV   R5, #1
  STR   R5, [R4]
.LendIfPressed:                 @ }
  B     .LretSystick
.LelseGameStarted:

  LDR   R4, =blink_countdown        @ if (countdown != 0) {
  LDR   R5, [R4]                    @
  CMP   R5, #0                      @
  BEQ   .LelseFire                  @

  SUB   R5, R5, #1                  @   countdown = countdown - 1;
  STR   R5, [R4]                    @

  B     .LendIfDelay                @ }

.LelseFire:                         @ else {

  LDR   R4, =i
  LDR   R5, [R4]

  LDR   R4, =random_value
  LDR   R6, [R4]

  CMP   R5, R6
  BGE   .LresetGame

  LDR   R4, =random_lights
  LDR   R7, [R4, R5, LSL #2]    @ get current light offset
  ADD   R7, R7, #LD4_PIN        @

  MOV   R6, #1                  @ get current light bit
  LSL   R6, R7                  @ 

  LDR   R4, =GPIOE_ODR
  LDR   R5, [R4]
  LDR   R7, =0xff00             @ turn off all lights
  BIC   R5, R7                  @

  ORR   R5, R6                  @ turn on current light
  STR   R5, [R4]                @


  LDR   R4, =i
  LDR   R5, [R4]
  ADD   R5, R5, #1
  STR   R5, [R4]
  B     .LskipResetGame
.LresetGame:
  LDR   R4, =i
  MOV   R5, #0
  STR   R5, [R4]

  LDR   R4, =GPIOE_ODR
  LDR   R5, [R4]
  LDR   R7, =0xff00             @ turn off all lights
  BIC   R5, R7                  @
  STR   R5, [R4]                @

  LDR   R4, =game_started
  MOV   R5, #0
  STR   R5, [R4]

  LDR   R4, =pressed_time
  MOV   R5, #0
  STR   R5, [R4]
.LskipResetGame:
  LDR   R4, =blink_countdown      @   countdown = BLINK_PERIOD;
  LDR   R5, =BLINK_PERIOD         @
  STR   R5, [R4]                  @

.LendIfDelay:                       @ }

.LretSystick:
  LDR     R4, =SCB_ICSR             @ Clear (acknowledge) the interrupt
  LDR     R5, =SCB_ICSR_PENDSTCLR   @
  STR     R5, [R4]                  @

  @ Return from interrupt handler
  POP  {R4-R7, PC}



@
@ External interrupt line 0 interrupt handler
@   (count button presses)
@
  .type  EXTI0_IRQHandler, %function
EXTI0_IRQHandler:

  PUSH  {R4-R7,LR}

  LDR   R4, =button_is_pressed
  LDR   R5, [R4]

  CMP   R5, #0                      @ if (!button_is_pressed) {
  BNE   .LnotReset
  LDR   R6, =pressed_time
  MOV   R7, #0
  STR   R7, [R6]                    @   pressed_time = 0
.LnotReset:                         @ }

  EOR   R5, #1                      @ button_is_pressed = !button_is_pressed
  STR   R5, [R4]


  LDR   R4, =SYSTICK_VAL
  LDR   R5, [R4]
  AND   R5, R5, #7                  @ random_value = (random_value % 8) + 5
  ADD   R5, R5, #5
  LDR   R4, =random_value
  STR   R5, [R4]

  LDR   R4, =button_count           @ count = count + 1
  LDR   R5, [R4]                    @
  ADD   R5, R5, #1                  @
  STR   R5, [R4]                    @

  LDR   R4, =EXTI_PR                @ Clear (acknowledge) the interrupt
  MOV   R5, #(1<<0)                 @
  STR   R5, [R4]                    @

  @ Return from interrupt handler
  POP  {R4-R7,PC}


  .section .data
  
button_count:
  .space  4

blink_countdown:
  .space  4

random_value:
  .space  4

game_started:
  .space  4

button_is_pressed:
  .space  4

pressed_time:
  .space  4

a:
  .space  4
c:
  .space  4
m:
  .space  4
random_lights:
  .space 400
i:
  .space 4
  .end